### ISSUE TITLE
Syntax error in Checkspps "Else"

### ISSUE THREAD

**Issue by GGSonoda** [Ulises-Rosas/OBc#2]
Hey there,
I'm getting syntax error on checkspps when running checklists. It seems there is this "else" with no correspondent if that's causing the issue (link below). I'm not sure if that's a resource of unix syntax which is unknown for me, or an error. Also, I tried commenting on such line to try a temporary fix, but then, there are two lines of consecutive double quotes that are causing "command not found " error. 
```
        check_inBackUp=$(cat backUp_bold | grep -Ee "^${POSITIONAL[@]},$spps_syns," )
"
"
```

https://github.com/Ulises-Rosas/OBc/blob/6b20b8237f16acea8fb8c42c0d4be2702eb8347c/circling_sh/checkspps#L286

Thanks in advance

**Comment by Ulises-Rosas** [comment]
I am very sorry for the late reply. I think there was some issues in the merging of branches with GitHub and that is why it ended deleting some lines unintentionally

**Comment by Ulises-Rosas** [comment]
I added the lines from previous commits. If it does not work, please open another issue. I will look for it
